unstable_features = true

format_code_in_doc_comments = true
format_macro_matchers = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
reorder_impl_items = true
wrap_comments = true
